### ISSUE TITLE
Performance on other category

### ISSUE THREAD

**Issue by Yishun99** [clinplayer/3DModelingRL#3]
Have you test the performance on more complex categories? Such as chair, which involves hole and non-convex part.

**Comment by clinplayer** [comment]
A limitation of our method is the reconstruction quality. The current setting can only work for the shapes that have simple and distinguishable structures. It is hard to capture the rewards for the detailed parts such as chair legs. Since this is the first exploration of using RL for 3D modeling, we will appreciate it if you have any insights to improve the modeling quality of RL.
