### ISSUE TITLE
Ground truth binvox

### ISSUE THREAD

**Issue by stephan000** [clinplayer/3DModelingRL#4]
Hi, 

Thank you for sharing codes.

I wonder how you generate ground truth voxels.
I would like to run this code in another class of the ShapeNet dataset.
I have used [binvox](https://www.patrickmin.com/binvox/) to generate a 64^3 voxel model from ShapeNet v2, but it does not match the model you are providing.
Specifically, the following commands were executed.
```binvox model_normalized.obj -d 64 -cb```

If there is no problem with the command, it is because of the version of binvox or my environment. So I won't worry about this anymore.
If you know of a better way, please let me know.

**Comment by clinplayer** [comment]
Hi, I think your command looks good. I remember we used a similar way to generate the voxelized shapes. What do you mean by "does not match"? Maybe some of our categories are not centralized, whereas I think these differences in scale or alignment do not affect the results too much because the primitives are distributed evenly in the voxel space. 

Note in this implementation you also need a low-resolution voxel in 16^3 for Prim-Agent for better efficiency and abstraction.

**Comment by stephan000** [comment]
Hi, 

> What do you mean by "does not match"? 

It means that the voxel data of the model you provide is different from the model obtained by the above command. The models look similar, so if scale and alignment don't affect the results, it doesn't matter.

Thank you.
